### PR TITLE
use anonymous field for serverState

### PR DESCRIPTION
**Pull request by haiyanmeng**
Signed-off-by: Haiyan Meng hmeng@redhat.com

### CODE REVIEW

**Comment by haiyanmeng** [comment]
@mrunalp , PTAL.
I was just trying to see whether `Server.serverState` is a good use case for anonymous fields. If you do not think so, I will cancel this PR.

**Comment by runcom** [comment]
@hmeng-19 I would not do this personally - anonymous fields are good with mutexes or where you're trying to accomplish some sort of object-oriented parent-child relationship - `state` is a good candidate for a named field instead to me.

**Comment by mrunalp** [comment]
Agree with @runcom. state will grow to have more fields as work on the code.

**Comment by haiyanmeng** [comment]
@runcom , @mrunalp , sounds good. Then I will close this.

**Pull request closed without merging**
