### PR TITLE
Add missing params into service handlers

### PR DESCRIPTION
**Pull request by haiyanmeng**
```
In `api.pb.go`, every handler in `_RuntimeService_serviceDesc.Methods` and
`_ImageService_serviceDesc`, such as `_RuntimeService_Version_Handler`, should
have another parameter, `interceptor grpc.UnaryServerInterceptor`, to match
`grpc.MethodDesc.Handler`.
```

### CODE REVIEW

**Comment by haiyanmeng** [comment]
@mrunalp , PTAL.

**Comment by mrunalp** [comment]
@hmeng-19 That file is supposed to be auto-generated. Not sure why it missed some fields. I picked these up from the original PR. We should probably try to generate the file again using protoc and see if we end up with the same diffs.

**Comment by haiyanmeng** [comment]
@mrunalp , one thing I am sure is that without adding these params, `go run cmd/server/main.go` would fail. 
After I added these params, I can test the ocid by running `go run cmd/server/main.go`.

Currently k8s is using some shell scripts to compile `api.proto` into `api.pb.go`. I did not really dig into their code and am not sure what they do.
However, I indeed left a note to the PR (https://github.com/kubernetes/kubernetes/pull/17048) to let them know the params are missing.

**Comment by mrunalp** [comment]
@hmeng-19 Hmm, it works for me without these changes:

```
[root@dhcp-16-129 ocid]# go build -o ocid cmd/server/main.go 
[root@dhcp-16-129 ocid]# ./ocid 
^C
[root@dhcp-16-129 ocid]# go run cmd/server/main.go 
^Csignal: interrupt
```

**Comment by haiyanmeng** [comment]
@mrunalp , really? Let me retry it.

**Comment by haiyanmeng** [comment]
```
@mrunalp , that is what I got. Still the same failure.

  [hmeng@localhost ocid]$ pwd
  /home/hmeng/go/src/github.com/mrunalp/ocid

   [hmeng@localhost ocid]$ git log
   commit 40592af124f1b6608f7148086b6c898c8e84190a
   Author: Mrunal Patel <mrunalp@gmail.com>
   Date:   Fri Jul 8 12:04:00 2016 -0700

       Add stubs for server implementation


[hmeng@localhost ocid]$ go build -o ocid cmd/server/main.go
# github.com/mrunalp/ocid/vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2666: cannot use _RuntimeService_Version_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2670: cannot use _RuntimeService_CreatePodSandbox_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2674: cannot use _RuntimeService_StopPodSandbox_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2678: cannot use _RuntimeService_DeletePodSandbox_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2682: cannot use _RuntimeService_PodSandboxStatus_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2686: cannot use _RuntimeService_ListPodSandbox_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2690: cannot use _RuntimeService_CreateContainer_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2694: cannot use _RuntimeService_StartContainer_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2698: cannot use _RuntimeService_StopContainer_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2702: cannot use _RuntimeService_RemoveContainer_Handler (type func(interface {}, context.Context, func(interface {}) error) (interface {}, error)) as type grpc.methodHandler in field value
vendor/github.com/kubernetes/kubernetes/pkg/kubelet/api/v1alpha1/runtime/api.pb.go:2702: too many errors
```

**Comment by mrunalp** [comment]
@hmeng-19 This seems like a versioning issue. I have pushed vendored dependencies to the repo. Could you try rebuilding?

**Comment by haiyanmeng** [comment]
@mrunalp , it works now. Thanks.

**Comment by mrunalp** [comment]
@hmeng-19 Awesome! Thanks for testing. Now we can work on the other items.

**Pull request closed without merging**
