### PR TITLE
Add API to get container network namespace path

### PR DESCRIPTION
**Pull request by mrunalp**
We need this for networking integration.

Signed-off-by: Mrunal Patel mrunalp@gmail.com

### CODE REVIEW

**Comment by mrunalp** [comment]
@rajatchopra PTAL

**Comment by rajatchopra** [comment]
Looks good.

**Comment by runcom** [comment]
Lgtm

**Comment by mrunalp** [comment]
Again git-validation gone bonkers. I don't see any issues locally so merging this. Thanks!

**Pull request merged**
